name = "SimpleUpdate"
uuid = "cc40038d-14bf-53fa-a31b-27dfa92ad5ad"
authors = ["Andreas Peter <andreas.peter.ch@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
