name = "SimpleUpdate"
uuid = "cc40038d-14bf-53fa-a31b-27dfa92ad5ad"
authors = ["Andreas Peter <andreas.peter.ch@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
TensorNetworkTensors = "9cd545fa-50e6-5d0b-b05c-fbfd5125ba2b"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
